POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "sowmya", "password": "someone1234!", "email": "sowmyakumaravel2002@gmail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "sowmya", "password": "someone1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 905aeea574d16e4acc73c0cbd164894e28e417ad